f_size_lab = 18;
f_size_ticks = 18;
f_size_legend = 14;

figure;
subplot(3,3,1); plot(time,x,'k','LineWidth',1.5); 
ylabel('$x$ (m)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,4); plot(time,y,'k','LineWidth',1.5); 
ylabel('$y$ (m)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,7); plot(time,z,'k','LineWidth',1.5); 
ylabel('$z$ (m)','FontSize',f_size_lab,'Interpreter','latex'); xlabel('Time (s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,2); plot(time,Vx,'k','LineWidth',1.5); 
ylabel('$u$ (m/s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,5); plot(time,Vy,'k','LineWidth',1.5); 
ylabel('$v$ (m/s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,8); plot(time,Vz,'k','LineWidth',1.5); 
ylabel('$w$ (m/s)','FontSize',f_size_lab,'Interpreter','latex'); xlabel('Time (s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,3); plot(time,ax,'k',time,fx,':r','LineWidth',1.5); hold on; plot(time,fx,':r','LineWidth',1.5);
ylabel('$a_x$ (m/s$^2$)','FontSize',f_size_lab,'Interpreter','latex'); 
legend('$a_x$','$f_x$','FontSize',f_size_legend,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,6); plot(time,ay,'k',time,fy,':r','LineWidth',1.5); hold on; plot(time,fy,':r','LineWidth',1.5);
ylabel('$a_y$ (m/s$^2$)','FontSize',f_size_lab,'Interpreter','latex'); 
legend('$a_y$','$f_y$','FontSize',f_size_legend,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,9); plot(time,az,'k',time,fz,':r','LineWidth',1.5); hold on; plot(time,fz,':r','LineWidth',1.5);
ylabel('$a_z$ (m/s$^2$)','FontSize',f_size_lab,'Interpreter','latex'); 
legend('$a_z$','$f_z$','FontSize',f_size_legend,'Interpreter','latex'); xlabel('Time (s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');

figure;
subplot(3,3,1); plot(time,phi*180/pi,'k','LineWidth',1.5); 
ylabel('$\phi$ ($^\circ$)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,4); plot(time,theta*180/pi,'k','LineWidth',1.5); 
ylabel('$\theta$ ($^\circ$)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,7); plot(time,psi*180/pi,'k','LineWidth',1.5); 
ylabel('$\psi$ ($^\circ$)','FontSize',f_size_lab,'Interpreter','latex'); xlabel('Time (s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,2); plot(time,wx*180/pi,'k','LineWidth',1.5); 
ylabel('$p$ ($^\circ$/s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,5); plot(time,wy*180/pi,'k','LineWidth',1.5); 
ylabel('$q$ ($^\circ$/s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,8); plot(time,wz*180/pi,'k','LineWidth',1.5); 
ylabel('$r$ ($^\circ$/s)','FontSize',f_size_lab,'Interpreter','latex'); xlabel('Time (s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,3); plot(time,lat*180/pi,'k','LineWidth',1.5); 
ylabel('$\varphi$ ($^\circ$)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,6); plot(time,lon*180/pi,'k','LineWidth',1.5); 
ylabel('$\lambda$ ($^\circ$)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
subplot(3,3,9); plot(time,h,'k','LineWidth',1.5); 
ylabel('$h$ (m)','FontSize',f_size_lab,'Interpreter','latex'); xlabel('Time (s)','FontSize',f_size_lab,'Interpreter','latex');
set(gca, 'FontSize', f_size_ticks, 'TickLabelInterpreter', 'latex');
